// <auto-generated />
using System;
using BlendMaster.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlendMaster.Migrations
{
    [DbContext(typeof(EnDbContext))]
    [Migration("20240613172326_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlendMaster.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryList");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Red Wine"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "White Wine"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sparkling Wine"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dessert Wine"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Rose Wine"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Fortified Wine"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Organic Wine"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Ice Wine"
                        });
                });

            modelBuilder.Entity("BlendMaster.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("OrderMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("TableID");

                    b.ToTable("OrderList");
                });

            modelBuilder.Entity("BlendMaster.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WineID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderID");

                    b.HasIndex("WineID");

                    b.ToTable("OrderDetailList");
                });

            modelBuilder.Entity("BlendMaster.Entities.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableId");

                    b.ToTable("TableList");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            TableName = "Table1"
                        },
                        new
                        {
                            TableId = 2,
                            TableName = "Table2"
                        },
                        new
                        {
                            TableId = 3,
                            TableName = "Table3"
                        },
                        new
                        {
                            TableId = 4,
                            TableName = "Table4"
                        },
                        new
                        {
                            TableId = 5,
                            TableName = "Table5"
                        },
                        new
                        {
                            TableId = 6,
                            TableName = "Table6"
                        },
                        new
                        {
                            TableId = 7,
                            TableName = "Table7"
                        },
                        new
                        {
                            TableId = 8,
                            TableName = "Table8"
                        });
                });

            modelBuilder.Entity("BlendMaster.Entities.Wine", b =>
                {
                    b.Property<int>("WineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WineId"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WineId");

                    b.ToTable("WineList");

                    b.HasData(
                        new
                        {
                            WineId = 1,
                            CategoryID = 1,
                            ImageUrl = "/images/wine1.jpg",
                            Introduction = "A smooth and fruity red wine, perfect for any occasion.",
                            Price = 35.50m,
                            WineName = "Merlot"
                        },
                        new
                        {
                            WineId = 2,
                            CategoryID = 1,
                            ImageUrl = "/images/wine2.jpg",
                            Introduction = "A bold red wine with notes of blackcurrant and a hint of oak.",
                            Price = 50.00m,
                            WineName = "Cabernet Sauvignon"
                        },
                        new
                        {
                            WineId = 3,
                            CategoryID = 1,
                            ImageUrl = "/images/wine3.jpg",
                            Introduction = "A delicate red wine with notes of cherry and spice.",
                            Price = 45.00m,
                            WineName = "Pinot Noir"
                        },
                        new
                        {
                            WineId = 4,
                            CategoryID = 1,
                            ImageUrl = "/images/wine4.jpg",
                            Introduction = "A robust red wine with rich flavors of blackberry and pepper.",
                            Price = 40.00m,
                            WineName = "Zinfandel"
                        },
                        new
                        {
                            WineId = 5,
                            CategoryID = 1,
                            ImageUrl = "/images/wine5.jpg",
                            Introduction = "A spicy and bold red wine with dark fruit flavors.",
                            Price = 55.00m,
                            WineName = "Syrah"
                        },
                        new
                        {
                            WineId = 6,
                            CategoryID = 1,
                            ImageUrl = "/images/wine6.jpg",
                            Introduction = "A full-bodied red wine with flavors of plum and black cherry.",
                            Price = 38.00m,
                            WineName = "Malbec"
                        },
                        new
                        {
                            WineId = 7,
                            CategoryID = 1,
                            ImageUrl = "/images/wine7.jpg",
                            Introduction = "A classic Italian red wine with flavors of dark cherry and oregano.",
                            Price = 42.00m,
                            WineName = "Sangiovese"
                        },
                        new
                        {
                            WineId = 8,
                            CategoryID = 2,
                            ImageUrl = "/images/wine8.jpg",
                            Introduction = "A popular white wine known for its rich and creamy flavor.",
                            Price = 29.99m,
                            WineName = "Chardonnay"
                        },
                        new
                        {
                            WineId = 9,
                            CategoryID = 2,
                            ImageUrl = "/images/wine9.jpg",
                            Introduction = "A crisp and refreshing white wine with hints of citrus.",
                            Price = 25.00m,
                            WineName = "Sauvignon Blanc"
                        },
                        new
                        {
                            WineId = 10,
                            CategoryID = 2,
                            ImageUrl = "/images/wine10.jpg",
                            Introduction = "A sweet white wine with floral aromas and a crisp finish.",
                            Price = 22.50m,
                            WineName = "Riesling"
                        },
                        new
                        {
                            WineId = 11,
                            CategoryID = 2,
                            ImageUrl = "/images/wine11.jpg",
                            Introduction = "A light and zesty white wine with hints of green apple and pear.",
                            Price = 30.00m,
                            WineName = "Pinot Grigio"
                        },
                        new
                        {
                            WineId = 12,
                            CategoryID = 2,
                            ImageUrl = "/images/wine12.jpg",
                            Introduction = "A aromatic white wine with notes of lychee and rose petals.",
                            Price = 35.00m,
                            WineName = "Gewürztraminer"
                        },
                        new
                        {
                            WineId = 13,
                            CategoryID = 2,
                            ImageUrl = "/images/wine13.jpg",
                            Introduction = "A sweet and fruity white wine with flavors of peach and apricot.",
                            Price = 20.00m,
                            WineName = "Moscato"
                        },
                        new
                        {
                            WineId = 14,
                            CategoryID = 2,
                            ImageUrl = "/images/wine14.jpg",
                            Introduction = "A full-bodied white wine with floral and tropical fruit notes.",
                            Price = 40.00m,
                            WineName = "Viognier"
                        },
                        new
                        {
                            WineId = 15,
                            CategoryID = 3,
                            ImageUrl = "/images/wine15.jpg",
                            Introduction = "A classic sparkling wine with crisp acidity and fine bubbles.",
                            Price = 60.00m,
                            WineName = "Champagne"
                        },
                        new
                        {
                            WineId = 16,
                            CategoryID = 3,
                            ImageUrl = "/images/wine16.jpg",
                            Introduction = "A light and refreshing sparkling wine with flavors of green apple and melon.",
                            Price = 25.00m,
                            WineName = "Prosecco"
                        },
                        new
                        {
                            WineId = 17,
                            CategoryID = 3,
                            ImageUrl = "/images/wine17.jpg",
                            Introduction = "A Spanish sparkling wine with zesty citrus flavors and fine bubbles.",
                            Price = 28.00m,
                            WineName = "Cava"
                        },
                        new
                        {
                            WineId = 18,
                            CategoryID = 3,
                            ImageUrl = "/images/wine18.jpg",
                            Introduction = "A French sparkling wine with delicate bubbles and notes of white peach.",
                            Price = 35.00m,
                            WineName = "Crémant"
                        },
                        new
                        {
                            WineId = 19,
                            CategoryID = 3,
                            ImageUrl = "/images/wine19.jpg",
                            Introduction = "A sweet and fruity sparkling wine with flavors of honey and apricot.",
                            Price = 20.00m,
                            WineName = "Asti Spumante"
                        },
                        new
                        {
                            WineId = 20,
                            CategoryID = 3,
                            ImageUrl = "/images/wine20.jpg",
                            Introduction = "A sparkling wine with flavors of strawberry and raspberry.",
                            Price = 30.00m,
                            WineName = "Sparkling Rosé"
                        },
                        new
                        {
                            WineId = 21,
                            CategoryID = 3,
                            ImageUrl = "/images/wine21.jpg",
                            Introduction = "A very dry sparkling wine with high acidity and mineral notes.",
                            Price = 45.00m,
                            WineName = "Brut Nature"
                        },
                        new
                        {
                            WineId = 22,
                            CategoryID = 4,
                            ImageUrl = "/images/wine22.jpg",
                            Introduction = "A rich and sweet fortified wine with flavors of dried fruit and spice.",
                            Price = 50.00m,
                            WineName = "Port"
                        },
                        new
                        {
                            WineId = 23,
                            CategoryID = 4,
                            ImageUrl = "/images/wine23.jpg",
                            Introduction = "A fortified wine with nutty flavors and hints of dried fruit.",
                            Price = 30.00m,
                            WineName = "Sherry"
                        },
                        new
                        {
                            WineId = 24,
                            CategoryID = 4,
                            ImageUrl = "/images/wine24.jpg",
                            Introduction = "A fortified wine with caramel and nutty flavors.",
                            Price = 40.00m,
                            WineName = "Madeira"
                        },
                        new
                        {
                            WineId = 25,
                            CategoryID = 4,
                            ImageUrl = "/images/wine25.jpg",
                            Introduction = "A sweet wine with honey and apricot flavors.",
                            Price = 55.00m,
                            WineName = "Sauternes"
                        },
                        new
                        {
                            WineId = 26,
                            CategoryID = 4,
                            ImageUrl = "/images/wine26.jpg",
                            Introduction = "A Hungarian sweet wine with flavors of peach and honey.",
                            Price = 60.00m,
                            WineName = "Tokaji"
                        },
                        new
                        {
                            WineId = 27,
                            CategoryID = 4,
                            ImageUrl = "/images/wine27.jpg",
                            Introduction = "A sweet wine made from frozen grapes, with intense fruit flavors.",
                            Price = 65.00m,
                            WineName = "Ice Wine"
                        },
                        new
                        {
                            WineId = 28,
                            CategoryID = 4,
                            ImageUrl = "/images/wine28.jpg",
                            Introduction = "A sweet wine with floral and fruity flavors.",
                            Price = 35.00m,
                            WineName = "Muscat"
                        },
                        new
                        {
                            WineId = 29,
                            CategoryID = 5,
                            ImageUrl = "/images/wine29.jpg",
                            Introduction = "A light and refreshing rosé with flavors of strawberry and citrus.",
                            Price = 25.00m,
                            WineName = "Provence Rosé"
                        },
                        new
                        {
                            WineId = 30,
                            CategoryID = 5,
                            ImageUrl = "/images/wine30.jpg",
                            Introduction = "A sweet rosé with flavors of cherry and raspberry.",
                            Price = 20.00m,
                            WineName = "White Zinfandel"
                        },
                        new
                        {
                            WineId = 31,
                            CategoryID = 5,
                            ImageUrl = "/images/wine31.jpg",
                            Introduction = "A dry rosé with flavors of watermelon and strawberry.",
                            Price = 30.00m,
                            WineName = "Grenache Rosé"
                        },
                        new
                        {
                            WineId = 32,
                            CategoryID = 5,
                            ImageUrl = "/images/wine32.jpg",
                            Introduction = "A bold rosé with flavors of raspberry and spice.",
                            Price = 35.00m,
                            WineName = "Syrah Rosé"
                        },
                        new
                        {
                            WineId = 33,
                            CategoryID = 5,
                            ImageUrl = "/images/wine33.jpg",
                            Introduction = "A delicate rosé with flavors of cherry and rose petals.",
                            Price = 28.00m,
                            WineName = "Pinot Noir Rosé"
                        },
                        new
                        {
                            WineId = 34,
                            CategoryID = 5,
                            ImageUrl = "/images/wine34.jpg",
                            Introduction = "A Spanish rosé with flavors of strawberry and peach.",
                            Price = 32.00m,
                            WineName = "Tempranillo Rosé"
                        },
                        new
                        {
                            WineId = 35,
                            CategoryID = 5,
                            ImageUrl = "/images/wine35.jpg",
                            Introduction = "A rosé with flavors of red currant and green pepper.",
                            Price = 40.00m,
                            WineName = "Cabernet Franc Rosé"
                        },
                        new
                        {
                            WineId = 36,
                            CategoryID = 6,
                            ImageUrl = "/images/wine36.jpg",
                            Introduction = "A fortified wine with flavors of caramel and vanilla.",
                            Price = 25.00m,
                            WineName = "Marsala"
                        },
                        new
                        {
                            WineId = 37,
                            CategoryID = 6,
                            ImageUrl = "/images/wine37.jpg",
                            Introduction = "A fortified wine with botanical flavors.",
                            Price = 20.00m,
                            WineName = "Vermouth"
                        },
                        new
                        {
                            WineId = 38,
                            CategoryID = 6,
                            ImageUrl = "/images/wine38.jpg",
                            Introduction = "A sweet fortified wine with flavors of dried fruit and honey.",
                            Price = 35.00m,
                            WineName = "Commandaria"
                        },
                        new
                        {
                            WineId = 39,
                            CategoryID = 6,
                            ImageUrl = "/images/wine39.jpg",
                            Introduction = "A fortified wine with flavors of chocolate and coffee.",
                            Price = 30.00m,
                            WineName = "Banyuls"
                        },
                        new
                        {
                            WineId = 40,
                            CategoryID = 6,
                            ImageUrl = "/images/wine40.jpg",
                            Introduction = "A fortified wine with flavors of apricot and almond.",
                            Price = 40.00m,
                            WineName = "Pineau des Charentes"
                        },
                        new
                        {
                            WineId = 41,
                            CategoryID = 6,
                            ImageUrl = "/images/wine41.jpg",
                            Introduction = "A fortified wine with flavors of caramel and nuts.",
                            Price = 45.00m,
                            WineName = "Madeira"
                        },
                        new
                        {
                            WineId = 42,
                            CategoryID = 6,
                            ImageUrl = "/images/wine42.jpg",
                            Introduction = "A fortified wine with nutty flavors.",
                            Price = 30.00m,
                            WineName = "Sherry"
                        },
                        new
                        {
                            WineId = 43,
                            CategoryID = 7,
                            ImageUrl = "/images/wine43.jpg",
                            Introduction = "An organic red wine with flavors of black cherry and plum.",
                            Price = 40.00m,
                            WineName = "Organic Merlot"
                        },
                        new
                        {
                            WineId = 44,
                            CategoryID = 7,
                            ImageUrl = "/images/wine44.jpg",
                            Introduction = "An organic white wine with flavors of apple and pear.",
                            Price = 35.00m,
                            WineName = "Organic Chardonnay"
                        },
                        new
                        {
                            WineId = 45,
                            CategoryID = 7,
                            ImageUrl = "/images/wine45.jpg",
                            Introduction = "An organic red wine with flavors of blackcurrant and oak.",
                            Price = 50.00m,
                            WineName = "Organic Cabernet Sauvignon"
                        },
                        new
                        {
                            WineId = 46,
                            CategoryID = 7,
                            ImageUrl = "/images/wine46.jpg",
                            Introduction = "An organic red wine with flavors of cherry and spice.",
                            Price = 45.00m,
                            WineName = "Organic Pinot Noir"
                        },
                        new
                        {
                            WineId = 47,
                            CategoryID = 7,
                            ImageUrl = "/images/wine47.jpg",
                            Introduction = "An organic white wine with flavors of citrus and melon.",
                            Price = 30.00m,
                            WineName = "Organic Sauvignon Blanc"
                        },
                        new
                        {
                            WineId = 48,
                            CategoryID = 7,
                            ImageUrl = "/images/wine48.jpg",
                            Introduction = "An organic red wine with flavors of blackberry and pepper.",
                            Price = 38.00m,
                            WineName = "Organic Zinfandel"
                        },
                        new
                        {
                            WineId = 49,
                            CategoryID = 7,
                            ImageUrl = "/images/wine49.jpg",
                            Introduction = "An organic red wine with flavors of dark fruit and spice.",
                            Price = 55.00m,
                            WineName = "Organic Syrah"
                        },
                        new
                        {
                            WineId = 50,
                            CategoryID = 8,
                            ImageUrl = "/images/wine50.jpg",
                            Introduction = "A sweet ice wine with flavors of honey and apricot.",
                            Price = 60.00m,
                            WineName = "Vidal Ice Wine"
                        },
                        new
                        {
                            WineId = 51,
                            CategoryID = 8,
                            ImageUrl = "/images/wine51.jpg",
                            Introduction = "A sweet ice wine with flavors of peach and citrus.",
                            Price = 65.00m,
                            WineName = "Riesling Ice Wine"
                        },
                        new
                        {
                            WineId = 52,
                            CategoryID = 8,
                            ImageUrl = "/images/wine52.jpg",
                            Introduction = "A sweet ice wine with flavors of strawberry and rhubarb.",
                            Price = 70.00m,
                            WineName = "Cabernet Franc Ice Wine"
                        },
                        new
                        {
                            WineId = 53,
                            CategoryID = 8,
                            ImageUrl = "/images/wine53.jpg",
                            Introduction = "A sweet ice wine with flavors of lychee and rose petals.",
                            Price = 75.00m,
                            WineName = "Gewürztraminer Ice Wine"
                        },
                        new
                        {
                            WineId = 54,
                            CategoryID = 8,
                            ImageUrl = "/images/wine54.jpg",
                            Introduction = "A sweet ice wine with flavors of apple and pear.",
                            Price = 55.00m,
                            WineName = "Chardonnay Ice Wine"
                        },
                        new
                        {
                            WineId = 55,
                            CategoryID = 8,
                            ImageUrl = "/images/wine55.jpg",
                            Introduction = "A sweet ice wine with flavors of blackberry and plum.",
                            Price = 80.00m,
                            WineName = "Merlot Ice Wine"
                        },
                        new
                        {
                            WineId = 56,
                            CategoryID = 8,
                            ImageUrl = "/images/wine56.jpg",
                            Introduction = "A sweet ice wine with flavors of cherry and spice.",
                            Price = 85.00m,
                            WineName = "Pinot Noir Ice Wine"
                        });
                });

            modelBuilder.Entity("BlendMaster.Entities.Order", b =>
                {
                    b.HasOne("BlendMaster.Entities.Table", null)
                        .WithMany()
                        .HasForeignKey("TableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlendMaster.Entities.OrderDetail", b =>
                {
                    b.HasOne("BlendMaster.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlendMaster.Entities.Wine", null)
                        .WithMany()
                        .HasForeignKey("WineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
