// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Entities;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Entities.Bill", b =>
                {
                    b.Property<Guid>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerOrderOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillId");

                    b.HasIndex("CustomerOrderOrderId");

                    b.HasIndex("TableId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("WebApplication2.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("48fe2be4-0d0f-44a7-a22d-6c5ecde7cde4"),
                            CategoryName = "Classic"
                        },
                        new
                        {
                            CategoryId = new Guid("d7ee74db-e0c0-4d5a-b236-51e2ee551b20"),
                            CategoryName = "Tropical"
                        },
                        new
                        {
                            CategoryId = new Guid("bdeb2a78-0127-48c9-b0ec-a69bd6b47d94"),
                            CategoryName = "Modern"
                        });
                });

            modelBuilder.Entity("WebApplication2.Entities.CustomerOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("TableId");

                    b.ToTable("CustomerOrder");
                });

            modelBuilder.Entity("WebApplication2.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("WebApplication2.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("7231940c-d749-4ced-b914-2ef21cccad25"),
                            CategoryId = new Guid("48fe2be4-0d0f-44a7-a22d-6c5ecde7cde4"),
                            Price = 12.99m,
                            ProductDescription = "A timeless cocktail featuring bourbon, sugar, and bitters.",
                            ProductName = "Old Fashioned"
                        },
                        new
                        {
                            ProductId = new Guid("f6788097-baf0-4b8d-adee-77b78b94e5e8"),
                            CategoryId = new Guid("48fe2be4-0d0f-44a7-a22d-6c5ecde7cde4"),
                            Price = 11.99m,
                            ProductDescription = "A sophisticated cocktail made with gin and vermouth, garnished with an olive.",
                            ProductName = "Martini"
                        },
                        new
                        {
                            ProductId = new Guid("593ab29d-3e7b-489c-b0ef-01be3d83fff2"),
                            CategoryId = new Guid("d7ee74db-e0c0-4d5a-b236-51e2ee551b20"),
                            Price = 10.99m,
                            ProductDescription = "A tropical mix of rum, lime juice, and orgeat syrup.",
                            ProductName = "Mai Tai"
                        },
                        new
                        {
                            ProductId = new Guid("6b9cb6c0-b4e6-4dcf-9c3b-f625567e74de"),
                            CategoryId = new Guid("d7ee74db-e0c0-4d5a-b236-51e2ee551b20"),
                            Price = 9.99m,
                            ProductDescription = "A creamy blend of rum, pineapple juice, and coconut cream.",
                            ProductName = "Pina Colada"
                        },
                        new
                        {
                            ProductId = new Guid("977736eb-aabd-471e-9b14-dc1d108083c4"),
                            CategoryId = new Guid("bdeb2a78-0127-48c9-b0ec-a69bd6b47d94"),
                            Price = 13.49m,
                            ProductDescription = "A sophisticated mix of vodka, coffee liqueur, and espresso.",
                            ProductName = "Espresso Martini"
                        },
                        new
                        {
                            ProductId = new Guid("242d227f-ee94-4d8a-9e0d-87ef7a65c40b"),
                            CategoryId = new Guid("bdeb2a78-0127-48c9-b0ec-a69bd6b47d94"),
                            Price = 10.49m,
                            ProductDescription = "A refreshing cocktail with gin, cucumber, lime, and mint.",
                            ProductName = "Cucumber Cooler"
                        });
                });

            modelBuilder.Entity("WebApplication2.Entities.Recipe", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("WebApplication2.Entities.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TableId");

                    b.ToTable("Table");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            TableName = "Table1"
                        },
                        new
                        {
                            TableId = 2,
                            TableName = "Table2"
                        },
                        new
                        {
                            TableId = 3,
                            TableName = "Table3"
                        },
                        new
                        {
                            TableId = 4,
                            TableName = "Table4"
                        },
                        new
                        {
                            TableId = 5,
                            TableName = "Table5"
                        });
                });

            modelBuilder.Entity("WebApplication2.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b18c94b5-8caf-4b8a-a25d-148f6d425b13"),
                            Email = "email@example.com",
                            Name = "Bartender",
                            Password = "$2a$11$pT.kvgXwJ2aksguJ1lb4jOKuBQFbV9MdVp7tJ7OXgDUsteveblGPa"
                        });
                });

            modelBuilder.Entity("WebApplication2.Entities.Bill", b =>
                {
                    b.HasOne("WebApplication2.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany()
                        .HasForeignKey("CustomerOrderOrderId");

                    b.HasOne("WebApplication2.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WebApplication2.Entities.CustomerOrder", b =>
                {
                    b.HasOne("WebApplication2.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WebApplication2.Entities.OrderDetail", b =>
                {
                    b.HasOne("WebApplication2.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication2.Entities.Product", b =>
                {
                    b.HasOne("WebApplication2.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication2.Entities.CustomerOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
